"""
SSM Parameter Store Terraform exporter.

Generates `aws_ssm_parameter` Terraform resources for:
  - PATH params (on-prem paths → S3 migration markers)
  - Credential-like params (PASSWORD, TOKEN, SECRET, PWD, KEY, PASS, CRED, AUTH)

Output: terraform/ssm_parameters.tf
"""

from __future__ import annotations

import re
import textwrap
from pathlib import Path
from typing import List, Tuple

from .models import ParamType, PrmFile, PrmParameter


# ---------------------------------------------------------------------------
# Credential name heuristic
# ---------------------------------------------------------------------------

_CRED_PATTERN = re.compile(
    r"\b(PASSWORD|TOKEN|SECRET|PWD|KEY|PASS|CRED|AUTH|API_KEY|ACCESS_KEY|"
    r"PRIVATE_KEY|CLIENT_SECRET|DB_PASS|DB_PWD)\b",
    re.IGNORECASE,
)


def _is_credential(name: str) -> bool:
    return bool(_CRED_PATTERN.search(name))


def _ssm_name(folder: str, param_name: str, env_var: str = "var.environment") -> str:
    """Build the SSM parameter path:  /{env}/{folder}/{param_name}"""
    safe_folder = re.sub(r"[^a-zA-Z0-9_/-]", "-", folder).lower()
    safe_param = re.sub(r"[^a-zA-Z0-9_/-]", "-", param_name).lower()
    return f"/${{{{ {env_var} }}}}/{safe_folder}/{safe_param}"


def _safe_tf(name: str) -> str:
    """Terraform resource identifier-safe name."""
    return re.sub(r"[^a-zA-Z0-9_]", "_", name).lower()


# ---------------------------------------------------------------------------
# Main export function
# ---------------------------------------------------------------------------

def export_ssm_terraform(prm_files: List[PrmFile], output_dir: Path) -> Path:
    """
    Generate `aws_ssm_parameter` Terraform resources from parsed .prm files.

    Includes:
      - PATH params (on-prem filesystem paths needing S3 migration)
      - Credential params (name matches _CRED_PATTERN)

    Returns the path of the written .tf file.
    """
    resources: List[Tuple[str, str, PrmParameter, str]] = []
    # (resource_name, ssm_path, param, param_type_label)

    seen_resource_names: set = set()

    for prm in prm_files:
        for section in prm.sections:
            folder = section.folder or "_global"
            for param_name, param in section.params.items():
                include = False
                param_type_label = "String"

                if param.param_type == ParamType.PATH:
                    include = True
                elif _is_credential(param_name):
                    include = True
                    param_type_label = "SecureString"

                if not include:
                    continue

                resource_name = _safe_tf(f"ssm_{folder}_{param_name}")
                # De-duplicate across sections
                if resource_name in seen_resource_names:
                    continue
                seen_resource_names.add(resource_name)

                ssm_path = _ssm_name(folder, param_name)
                resources.append((resource_name, ssm_path, param, param_type_label))

    if not resources:
        # Write an empty placeholder so the file is always created
        tf_content = textwrap.dedent("""\
            # ---------------------------------------------------------------
            # SSM Parameter Store resources
            # Generated by param-translator export-ssm
            # No PATH or credential params found in the provided .prm files.
            # ---------------------------------------------------------------
        """)
    else:
        blocks = [textwrap.dedent("""\
            # ---------------------------------------------------------------
            # SSM Parameter Store resources
            # Generated by param-translator export-ssm
            #
            # SecureString params require KMS key: var.ssm_kms_key_id
            # String params store PATH values for on-prem → S3 migration
            # ---------------------------------------------------------------

            variable "ssm_kms_key_id" {
              description = "KMS key ID for encrypting SSM SecureString parameters"
              type        = string
              default     = "alias/aws/ssm"
            }

        """)]

        for resource_name, ssm_path, param, param_type_label in resources:
            raw_val = param.normalized_value or param.raw_value or ""
            # Escape any double quotes in value
            escaped_val = raw_val.replace('"', '\\"')
            kms_block = ""
            if param_type_label == "SecureString":
                kms_block = "\n  key_id = var.ssm_kms_key_id"

            blocks.append(textwrap.dedent(f"""\
                resource "aws_ssm_parameter" "{resource_name}" {{
                  name  = "{ssm_path}"
                  type  = "{param_type_label}"
                  value = "{escaped_val}"  # TODO: update with environment-specific value{kms_block}

                  tags = {{
                    ManagedBy   = "terraform"
                    Environment = var.environment
                    MigratedFrom = "InformaticaPowerCenter"
                  }}
                }}

            """))

        tf_content = "\n".join(blocks)

    out_path = output_dir / "terraform" / "ssm_parameters.tf"
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(tf_content, encoding="utf-8")
    return out_path
