"""
AWS Glue PySpark script builder.

Traverses the pipeline graph in topological order and emits idiomatic
PySpark code for each transformation type.

Supported transformations:
  SOURCE_QUALIFIER   — JDBC (SQL Server), FLAT FILE (delimited + fixed-width), Excel
  EXPRESSION         — withColumn() calls, translated via expr_translator
  FILTER             — df.filter() with translated condition
  AGGREGATOR         — groupBy() + agg()
  JOINER             — df.join() with translated condition
  LOOKUP             — broadcast join
  ROUTER             — df.filter() fan-out into multiple DataFrames
  UPDATE_STRATEGY    — insertInto / merge stub with TODO
  SEQUENCE_GENERATOR — monotonically_increasing_id()
  SORTER             — df.orderBy()
  NORMALIZER         — explode() stub with TODO (complex, needs manual review)
  TARGET             — JDBC write, S3 Parquet/Delta write

HIPAA note: generated scripts include a logging guard that prevents
column values from appearing in log output. Column names are logged
at INFO level but values only at DEBUG (which should be disabled in prod).
"""

from __future__ import annotations
from datetime import datetime, timezone
from typing import Dict, List, Optional, Set, Tuple

from pc_extractor.models import (
    FolderDef, MappingDef, SourceDef, TargetDef, TransformationDef,
    TransformationType,
)
from .graph import PipelineGraph, PipelineNode
from .expr_translator import translate, translate_filter, translate_join_condition, Confidence


# ---------------------------------------------------------------------------
# JDBC connection type mapping (PC db type → Glue connection_type)
# ---------------------------------------------------------------------------

_JDBC_CONN_TYPE = {
    "microsoft sql server": "sqlserver",
    "sql server":           "sqlserver",
    "oracle":               "oracle",
    "mysql":                "mysql",
    "mariadb":              "mysql",
    "postgresql":           "postgresql",
    "redshift":             "redshift",
    "db2":                  "db2",
    "teradata":             "teradata",
    "snowflake":            "custom",   # Snowflake uses JDBC option
}

_LAKEHOUSE_TYPES = {"delta", "s3", "parquet", "orc", "iceberg", "glue catalog"}


def _glue_conn_type(db_type: str) -> str:
    return _JDBC_CONN_TYPE.get(db_type.lower(), "jdbc")


def _is_lakehouse(db_type: str) -> bool:
    return db_type.lower() in _LAKEHOUSE_TYPES


def _safe_var(name: str) -> str:
    """Convert any string to a safe Python identifier."""
    import re
    return re.sub(r"[^a-z0-9_]", "_", name.lower()).strip("_")


def _arg_name(connection_hint: str) -> str:
    """Glue job arg name for a connection (uppercase, no spaces)."""
    return _safe_var(connection_hint).upper()


# ---------------------------------------------------------------------------
# Script sections builder
# ---------------------------------------------------------------------------

class GlueScriptBuilder:
    """Accumulates code sections and renders the final script."""

    def __init__(self, mapping_name: str, folder_name: str) -> None:
        self.mapping_name = mapping_name
        self.folder_name = folder_name
        self._imports: List[str] = []
        self._args: List[str] = []             # getResolvedOptions arg names
        self._body: List[str] = []             # main job body lines
        self._warnings: List[str] = []

    # -- public helpers --

    def add_arg(self, arg: str) -> None:
        if arg not in self._args:
            self._args.append(arg)

    def add_import(self, imp: str) -> None:
        if imp not in self._imports:
            self._imports.append(imp)

    def emit(self, *lines: str) -> None:
        self._body.extend(lines)

    def warn(self, msg: str) -> None:
        self._warnings.append(msg)
        self._body.append(f"# WARNING: {msg}")

    def todo(self, msg: str) -> None:
        self._body.append(f"# TODO: {msg}")

    def section(self, title: str) -> None:
        self._body.append("")
        self._body.append(f"# {'=' * 58}")
        self._body.append(f"# {title}")
        self._body.append(f"# {'=' * 58}")

    # -- render --

    def render(self, score: int, platform: str) -> str:
        ts = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
        warnings_block = ""
        if self._warnings:
            warnings_block = "# WARNINGS:\n" + "\n".join(f"#   {w}" for w in self._warnings) + "\n\n"

        extra_imports = ""
        if self._imports:
            extra_imports = "\n" + "\n".join(self._imports)

        if self._args:
            args_block = "    'JOB_NAME',\n    " + ",\n    ".join(f"'{a}'" for a in self._args) + ","
        else:
            args_block = "    'JOB_NAME',"

        body = "\n".join(self._body)

        return f"""\
# =============================================================
# Generated by pc-extractor glue-gen
# Source mapping : {self.mapping_name}
# Folder         : {self.folder_name}
# Complexity score: {score}  |  Platform: {platform}
# Generated      : {ts}
# REVIEW REQUIRED: See any TODO/WARNING comments below
# =============================================================
# HIPAA NOTE: This job may process regulated data.
#   - Do NOT log column values at INFO level.
#   - Enable Glue job bookmarks to avoid reprocessing.
#   - Ensure the Glue connection uses SSL/TLS.
#   - Validate IAM role has least-privilege S3/RDS access.
# =============================================================
{warnings_block}import sys{extra_imports}
from awsglue.utils import getResolvedOptions
from pyspark.context import SparkContext
from awsglue.context import GlueContext
from awsglue.job import Job
from pyspark.sql import functions as F
from pyspark.sql.types import *
import logging

logger = logging.getLogger()
logger.setLevel(logging.INFO)

# --- Job parameters ---
args = getResolvedOptions(sys.argv, [
{args_block}
])

sc = SparkContext()
glueContext = GlueContext(sc)
spark = glueContext.spark_session
job = Job(glueContext)
job.init(args['JOB_NAME'], args)

{body}

job.commit()
logger.info("Job %s completed successfully", args['JOB_NAME'])
"""


# ---------------------------------------------------------------------------
# Main code builder
# ---------------------------------------------------------------------------

class GlueJobCodeBuilder:

    def __init__(
        self,
        mapping: MappingDef,
        folder: FolderDef,
    ) -> None:
        self.mapping = mapping
        self.folder = folder
        # Build transformation lookup from mapping
        self._xform_lookup: Dict[str, TransformationDef] = {
            t.name: t for t in mapping.transformations
        }
        self.graph = PipelineGraph.from_mapping(mapping, self._xform_lookup)
        self.script = GlueScriptBuilder(mapping.name, mapping.folder)
        # Track which df var name each node produces
        self._node_output: Dict[str, str] = {}
        # Router group wiring: downstream_instance_name → correct group df var
        # Populated by _build_router so each successor gets the right group DataFrame.
        self._node_group_wiring: Dict[str, str] = {}

    def build(self) -> Tuple[str, List[str]]:
        """
        Build the Glue PySpark script.
        Returns (script_text, warnings_list).
        """
        g = self.graph
        s = self.script

        # Collect job parameters from mapping variables
        for var in self.mapping.variables:
            if var.is_param:
                arg = _arg_name(var.name.lstrip("$"))
                s.add_arg(arg)

        # Walk the pipeline in topological order
        for node in g.topological_order():
            if g.is_source_instance(node):
                # Raw source nodes (SOURCE type) — data is read via their SQ
                continue

            if g.is_target(node):
                self._build_target(node)
            elif g.is_source_qualifier(node):
                self._build_source_qualifier(node)
            else:
                t_def = node.transformation_def
                if t_def is None:
                    s.warn(f"No transformation definition found for instance '{node.instance_name}'")
                    continue
                self._dispatch_transformation(node, t_def)

        score = self.mapping.complexity_score or 1
        platform = self.mapping.target_platform.value if self.mapping.target_platform else "GLUE"
        return s.render(score, platform), self.script._warnings

    def _resolve_in_df(self, node_name: str, upstream: Optional[str]) -> str:
        """
        Resolve the input DataFrame variable for a node.
        Checks Router group wiring first (so nodes downstream of a Router
        get the correct group DataFrame, not always the first group).
        """
        if node_name in self._node_group_wiring:
            return self._node_group_wiring[node_name]
        return self._node_output.get(upstream, "df_UNKNOWN") if upstream else "df_UNKNOWN"

    # ------------------------------------------------------------------
    # Source Qualifier
    # ------------------------------------------------------------------

    def _build_source_qualifier(self, node: PipelineNode) -> None:
        g = self.graph
        s = self.script
        t = node.transformation_def
        df_var = g.df_var(node.instance_name)
        self._node_output[node.instance_name] = df_var

        # Find the source instance that feeds this SQ
        source_inst_names = [
            e.from_node for e in g.fields_flowing_into(node.instance_name)
        ]
        source_inst_name = source_inst_names[0] if source_inst_names else None
        source_node = g.nodes.get(source_inst_name) if source_inst_name else None
        src_def: Optional[SourceDef] = None

        if source_node:
            src_def = self.folder.sources.get(source_node.transformation_name)

        db_type = src_def.db_type if src_def else "Unknown"
        db_name = src_def.db_name if src_def else ""
        owner = (src_def.owner + ".") if (src_def and src_def.owner) else ""
        src_name = source_node.transformation_name if source_node else node.transformation_name

        s.section(
            f"SOURCE: {src_name}  ({db_type} / {db_name})\n"
            f"# PC Transformation: {node.instance_name}"
        )
        s.emit(f"logger.info('Reading source: {src_name}')")

        if db_type.upper() == "FLAT FILE":
            self._build_flat_file_source(node, src_def, df_var)
        elif db_type.upper() in ("EXCEL", "MICROSOFT EXCEL"):
            self._build_excel_source(node, src_def, df_var)
        elif _is_lakehouse(db_type):
            self._build_lakehouse_source(node, src_def, df_var)
        else:
            self._build_jdbc_source(node, src_def, src_name, owner, df_var, db_type, sq_def=t)

        # Apply source filter if present (SQ filter condition, not SQL override)
        if t and t.filter_condition:
            filt = translate_filter(t.filter_condition)
            if filt.confidence == Confidence.LOW:
                s.warn(f"Low-confidence filter translation on {node.instance_name}: {t.filter_condition!r}")
            s.emit("")
            s.emit(f"# Source filter: {t.filter_condition}")
            s.emit(f"{df_var} = {df_var}.filter({filt.pyspark_expr})")

    def _build_jdbc_source(
        self, node: PipelineNode, src_def: Optional[SourceDef],
        src_name: str, owner: str, df_var: str, db_type: str,
        sq_def: Optional[TransformationDef] = None,
    ) -> None:
        s = self.script
        conn_key = (src_def.db_name if src_def and src_def.db_name else src_name)
        conn_arg = _arg_name(f"CONN_{conn_key}")
        s.add_arg(conn_arg)
        table_name = src_def.name if src_def else src_name
        table_ref = f"{owner}{table_name}"

        # Use SQL override as a JDBC subquery when present — avoids full table scan.
        if sq_def and sq_def.sql_query:
            alias = f"pc_sq_{_safe_var(src_name)}"
            dbtable = f"({sq_def.sql_query}) AS {alias}"
            s.emit(f"# SQL override from PC Source Qualifier — executed as JDBC subquery")
        else:
            dbtable = table_ref

        conn_var = f"_conn_{_safe_var(conn_key)}"
        s.emit(f'{conn_var} = glueContext.extract_jdbc_conf(args["{conn_arg}"])')
        s.emit(f"{df_var} = (spark.read")
        s.emit(f'    .format("jdbc")')
        s.emit(f'    .option("url", {conn_var}["url"])')
        s.emit(f'    .option("dbtable", "{dbtable}")')
        s.emit(f'    .option("user", {conn_var}["user"])')
        s.emit(f'    .option("password", {conn_var}["password"])')
        s.emit(f"    .load()")
        s.emit(f")")

    def _build_flat_file_source(
        self, node: PipelineNode, src_def: Optional[SourceDef], df_var: str
    ) -> None:
        s = self.script
        src_safe = _safe_var(src_def.name if src_def else node.transformation_name)
        path_arg = _arg_name(f"S3_INPUT_PATH_{src_safe}")
        s.add_arg(path_arg)

        if src_def and src_def.is_fixed_width:
            self._build_fixed_width_source(node, src_def, df_var, path_arg)
        else:
            delim = src_def.delimiter if (src_def and src_def.delimiter) else ","
            s.emit(f"{df_var} = spark.read \\")
            s.emit(f'    .option("header", "true") \\')
            s.emit(f'    .option("sep", "{delim}") \\')
            s.emit(f'    .option("inferSchema", "false") \\')
            if src_def and src_def.fields:
                schema_lines = self._build_schema(src_def)
                s.emit(f"    .schema(StructType([")
                for sl in schema_lines:
                    s.emit(f"        {sl}")
                s.emit(f"    ])) \\")
            s.emit(f'    .csv(args["{path_arg}"])')

    def _build_fixed_width_source(
        self, node: PipelineNode, src_def: SourceDef, df_var: str, path_arg: str
    ) -> None:
        s = self.script
        s.emit(f"# Fixed-width file — reading as text then splitting by position")

        if not src_def.fields:
            s.warn(f"Fixed-width source {src_def.name} has no field definitions — cannot determine column positions")
            s.emit(f'{df_var} = spark.read.text(args["{path_arg}"])')
            return

        # Generate field position parsing code
        # PowerCenter fixed-width uses LENGTH to determine positions
        positions: List[Tuple[str, int, int]] = []
        pos = 0
        for f in src_def.fields:
            length = f.length or f.precision
            if not length:
                s.warn(
                    f"Fixed-width field '{f.name}' in source '{src_def.name}' has no "
                    "length/precision — defaulting to 1; verify source layout"
                )
                length = 1
            positions.append((f.name, pos, pos + length))
            pos += length

        raw_var = f"_raw_{_safe_var(src_def.name)}"
        s.emit(f'{raw_var} = spark.read.text(args["{path_arg}"])')
        s.emit(f"{df_var} = {raw_var}.select(")
        for fname, start, end in positions:
            s.emit(f'    F.substring(F.col("value"), {start + 1}, {end - start}).alias("{fname}"),')
        s.emit(f")")

        # Trim space-padding from CHAR/VARCHAR columns (fixed-width convention)
        str_fields = [
            f.name for f in src_def.fields
            if f.datatype.lower() in ("char", "nchar", "varchar", "nvarchar", "string")
        ]
        if str_fields:
            s.emit(f"# Trim space-padding from fixed-width CHAR columns")
            for fname in str_fields:
                s.emit(f'{df_var} = {df_var}.withColumn("{fname}", F.trim(F.col("{fname}")))')

    def _build_excel_source(
        self, node: PipelineNode, src_def: Optional[SourceDef], df_var: str
    ) -> None:
        s = self.script
        s.add_import("import pandas as _pd")
        src_name = src_def.name if src_def else node.transformation_name
        path_arg = _arg_name(f"S3_INPUT_PATH_{_safe_var(src_name)}")
        sheet_arg = _arg_name(f"EXCEL_SHEET_{_safe_var(src_name)}")
        s.add_arg(path_arg)
        s.add_arg(sheet_arg)

        s.emit(f"# Excel source — read via pandas then convert to Spark DataFrame")
        s.emit(f"# NOTE: For large Excel files consider converting to CSV/Parquet upstream")
        s.emit(f"_pdf_{_safe_var(src_name)} = _pd.read_excel(")
        s.emit(f'    args["{path_arg}"],')
        s.emit(f'    sheet_name=args["{sheet_arg}"],')
        s.emit(f"    dtype=str,   # read all as string, cast below")
        s.emit(f")")
        s.emit(f"{df_var} = spark.createDataFrame(_pdf_{_safe_var(src_name)})")

    def _build_lakehouse_source(
        self, node: PipelineNode, src_def: Optional[SourceDef], df_var: str
    ) -> None:
        s = self.script
        src_safe = _safe_var(src_def.name if src_def else node.transformation_name)
        path_arg = _arg_name(f"S3_INPUT_PATH_{src_safe}")
        s.add_arg(path_arg)
        db_type = src_def.db_type.lower() if src_def else "parquet"
        fmt = "delta" if "delta" in db_type else "parquet"
        s.emit(f'{df_var} = spark.read.format("{fmt}").load(args["{path_arg}"])')

    def _build_schema(self, src_def: SourceDef) -> List[str]:
        """Generate StructType field lines for a source definition."""
        _type_map = {
            "int": "IntegerType()", "integer": "IntegerType()",
            "bigint": "LongType()", "smallint": "ShortType()",
            "tinyint": "ByteType()",
            "decimal": "DecimalType({precision}, {scale})",
            "numeric": "DecimalType({precision}, {scale})",
            "float": "DoubleType()", "double": "DoubleType()",
            "real": "FloatType()",
            "varchar": "StringType()", "nvarchar": "StringType()",
            "char": "StringType()", "nchar": "StringType()",
            "string": "StringType()", "text": "StringType()",
            "date": "DateType()",
            "datetime": "TimestampType()", "datetime2": "TimestampType()",
            "timestamp": "TimestampType()",
            "bit": "BooleanType()", "boolean": "BooleanType()",
            "binary": "BinaryType()", "varbinary": "BinaryType()",
        }
        lines = []
        for f in src_def.fields:
            dt = f.datatype.lower()
            spark_type = _type_map.get(dt, "StringType()")
            if "{precision}" in spark_type:
                spark_type = spark_type.format(precision=f.precision or 18, scale=f.scale or 2)
            nullable = "True" if f.nullable else "False"
            lines.append(f'StructField("{f.name}", {spark_type}, {nullable}),')
        return lines

    # ------------------------------------------------------------------
    # Expression
    # ------------------------------------------------------------------

    def _build_expression(self, node: PipelineNode, t: TransformationDef) -> None:
        g = self.graph
        s = self.script
        upstream = g.primary_upstream(node.instance_name)
        in_df = self._resolve_in_df(node.instance_name, upstream)
        out_df = g.df_var(node.instance_name)
        self._node_output[node.instance_name] = out_df

        s.section(f"EXPRESSION: {node.instance_name}")
        s.emit(f"logger.info('Applying expressions: {node.instance_name}')")
        s.emit(f"{out_df} = {in_df}")

        # Only emit withColumn for OUTPUT ports that have a non-trivial expression
        for port in t.ports:
            if port.port_type not in ("OUTPUT", "INPUT/OUTPUT"):
                continue
            expr = port.expression.strip() if port.expression else ""
            if not expr or expr == port.name:
                continue   # pass-through, no withColumn needed
            result = translate(expr)
            if result.confidence == Confidence.LOW:
                s.warn(
                    f"Low-confidence expression translation for port {port.name} "
                    f"in {node.instance_name}: {expr!r}"
                )
                s.emit(f"# TODO: Verify translation of: {expr}")
            s.emit(
                f"{out_df} = {out_df}.withColumn("
                f'"{port.name}", {result.pyspark_expr})'
            )

    # ------------------------------------------------------------------
    # Filter
    # ------------------------------------------------------------------

    def _build_filter(self, node: PipelineNode, t: TransformationDef) -> None:
        g = self.graph
        s = self.script
        upstream = g.primary_upstream(node.instance_name)
        in_df = self._resolve_in_df(node.instance_name, upstream)
        out_df = g.df_var(node.instance_name)
        self._node_output[node.instance_name] = out_df

        condition = t.filter_condition or t.attributes.get("Filter Condition", "")
        s.section(f"FILTER: {node.instance_name}")
        if condition:
            result = translate_filter(condition)
            if result.confidence == Confidence.LOW:
                s.warn(f"Low-confidence filter: {condition!r}")
            s.emit(f"# PC condition: {condition}")
            s.emit(f"{out_df} = {in_df}.filter({result.pyspark_expr})")
        else:
            s.todo(f"Filter condition not found for {node.instance_name} — add filter logic")
            s.emit(f"{out_df} = {in_df}  # TODO: add filter condition")

    # ------------------------------------------------------------------
    # Aggregator
    # ------------------------------------------------------------------

    def _build_aggregator(self, node: PipelineNode, t: TransformationDef) -> None:
        g = self.graph
        s = self.script
        upstream = g.primary_upstream(node.instance_name)
        in_df = self._resolve_in_df(node.instance_name, upstream)
        out_df = g.df_var(node.instance_name)
        self._node_output[node.instance_name] = out_df

        s.section(f"AGGREGATOR: {node.instance_name}")

        # Separate group-by ports (INPUT/OUTPUT, no aggregate expression)
        # from aggregate ports (OUTPUT with SUM/COUNT/AVG/etc.)
        groupby_cols: List[str] = []
        agg_exprs: List[str] = []

        for port in t.ports:
            expr = (port.expression or "").strip()
            has_agg = any(
                fn in expr.upper()
                for fn in ("SUM(", "COUNT(", "AVG(", "MIN(", "MAX(", "FIRST(", "LAST(", "MEDIAN(")
            )
            if port.port_type == "INPUT/OUTPUT" and not has_agg:
                groupby_cols.append(f'"{port.name}"')
            elif port.port_type == "OUTPUT" and has_agg:
                result = translate(expr)
                if result.confidence == Confidence.LOW:
                    s.warn(f"Low-confidence agg expression for {port.name}: {expr!r}")
                agg_exprs.append(
                    f"{result.pyspark_expr}.alias(\"{port.name}\")"
                )

        if groupby_cols:
            gb = ", ".join(groupby_cols)
            if agg_exprs:
                agg = ",\n        ".join(agg_exprs)
                s.emit(f"logger.info('Aggregating: {node.instance_name}')")
                s.emit(f"{out_df} = {in_df}.groupBy({gb}).agg(")
                s.emit(f"    {agg},")
                s.emit(f")")
            else:
                s.todo(f"No aggregate expressions found in {node.instance_name}")
                s.emit(f"{out_df} = {in_df}.groupBy({gb}).count()")
        else:
            # Global aggregation
            if agg_exprs:
                agg = ",\n    ".join(agg_exprs)
                s.emit(f"{out_df} = {in_df}.agg({agg})")
            else:
                s.todo(f"Empty aggregator {node.instance_name} — add groupBy/agg logic")
                s.emit(f"{out_df} = {in_df}")

    # ------------------------------------------------------------------
    # Joiner
    # ------------------------------------------------------------------

    def _build_joiner(self, node: PipelineNode, t: TransformationDef) -> None:
        g = self.graph
        s = self.script
        all_upstream = g.all_upstream_names(node.instance_name)
        out_df = g.df_var(node.instance_name)
        self._node_output[node.instance_name] = out_df

        if len(all_upstream) < 2:
            s.warn(f"JOINER {node.instance_name} has fewer than 2 inputs — check connector definitions")
            left_df = self._node_output.get(all_upstream[0], "df_UNKNOWN") if all_upstream else "df_UNKNOWN"
            s.emit(f"{out_df} = {left_df}  # TODO: add second input to join")
            return

        left_df  = self._node_output.get(all_upstream[0], "df_left")
        right_df = self._node_output.get(all_upstream[1], "df_right")

        # Determine join type
        join_type_map = {
            "normal join":        "inner",
            "master outer join":  "left",
            "detail outer join":  "right",
            "full outer join":    "outer",
        }
        pc_join_type = (t.join_type or "Normal Join").lower()
        spark_join_type = join_type_map.get(pc_join_type, "inner")

        join_cond = t.join_condition or ""
        cond_result = translate_join_condition(join_cond)

        s.section(
            f"JOINER: {node.instance_name}\n"
            f"# Join type: {t.join_type or 'Normal'}  |  Condition: {join_cond}"
        )
        if cond_result.notes:
            for note in cond_result.notes:
                s.emit(f"# NOTE: {note}")

        s.emit(f"logger.info('Joining: {node.instance_name}')")
        s.emit(f"{out_df} = {left_df}.join(")
        s.emit(f"    {right_df},")
        s.emit(f"    on={cond_result.pyspark_expr},")
        s.emit(f'    how="{spark_join_type}",')
        s.emit(f")")

        # Spark deduplicates the join key automatically when `on` is a column name
        # string or list (same-name equi-join). For expression-form joins and any
        # non-key columns shared by both DataFrames, ambiguous references will raise
        # AnalysisException at runtime. Drop or alias right-side duplicates as needed.
        on_expr = cond_result.pyspark_expr.strip()
        is_simple_equi = (
            on_expr.startswith('"') or on_expr.startswith('[')
        )
        if not is_simple_equi:
            s.warn(
                f"JOINER {node.instance_name}: complex join condition — if {left_df} and "
                f"{right_df} share non-key column names, downstream references will be "
                f"ambiguous. Drop or alias duplicates after the join."
            )
            s.emit(f"# If column name conflicts exist, resolve with:")
            s.emit(f"# {out_df} = {out_df}.drop({right_df}['COLUMN_NAME'])  # repeat per conflict")

    # ------------------------------------------------------------------
    # Lookup
    # ------------------------------------------------------------------

    def _build_lookup(self, node: PipelineNode, t: TransformationDef) -> None:
        g = self.graph
        s = self.script
        upstream = g.primary_upstream(node.instance_name)
        in_df = self._resolve_in_df(node.instance_name, upstream)
        out_df = g.df_var(node.instance_name)
        self._node_output[node.instance_name] = out_df

        lkp_table = t.attributes.get("Lookup Table Name", "UNKNOWN_LOOKUP_TABLE")
        lkp_db = (
            t.attributes.get("Lookup Database Name")
            or t.attributes.get("Connection Information")
            or lkp_table
        )
        lkp_conn_arg = _arg_name(f"CONN_LKP_{lkp_db}")
        s.add_arg(lkp_conn_arg)

        lkp_condition = t.lookup_condition or ""
        cond_result = translate_join_condition(lkp_condition)

        # Output ports from the lookup (LKP_ prefixed ports)
        lkp_output_ports = [
            p for p in t.ports
            if p.port_type in ("OUTPUT", "RETURN VALUE") and p.name.upper().startswith("LKP_")
        ]
        select_exprs = [f'"{p.name}"' for p in lkp_output_ports] if lkp_output_ports else ["*"]

        s.section(
            f"LOOKUP: {node.instance_name}\n"
            f"# Lookup table: {lkp_table}  |  Condition: {lkp_condition}"
        )
        s.emit(f"logger.info('Loading lookup table: {lkp_table}')")
        lkp_df_var = f"df_lkp_{_safe_var(node.instance_name)}"
        lkp_conn_var = f"_conn_lkp_{_safe_var(node.instance_name)}"
        s.emit(f'{lkp_conn_var} = glueContext.extract_jdbc_conf(args["{lkp_conn_arg}"])')
        s.emit(f"{lkp_df_var} = (spark.read")
        s.emit(f'    .format("jdbc")')
        s.emit(f'    .option("url", {lkp_conn_var}["url"])')
        s.emit(f'    .option("dbtable", "{lkp_table}")')
        s.emit(f'    .option("user", {lkp_conn_var}["user"])')
        s.emit(f'    .option("password", {lkp_conn_var}["password"])')
        s.emit(f"    .load()")
        s.emit(f")")
        s.emit(f"# Broadcast hint for small lookup tables")
        s.emit(f"df_lkp_{_safe_var(node.instance_name)} = F.broadcast(df_lkp_{_safe_var(node.instance_name)})")
        s.emit(f"")
        s.emit(f"{out_df} = {in_df}.join(")
        s.emit(f"    df_lkp_{_safe_var(node.instance_name)},")
        s.emit(f"    on={cond_result.pyspark_expr},")
        s.emit(f'    how="left",   # PC default: return null on no match')
        s.emit(f")")
        # Always select to drop lookup table's non-output columns and avoid duplicates
        lkp_col_exprs = (
            [f'F.col("{p.name}")' for p in lkp_output_ports]
            if lkp_output_ports else []
        )
        s.emit(f"# Keep input columns plus lookup output ports; drop all other lookup columns")
        s.emit(f"{out_df} = {out_df}.select(")
        s.emit(f"    [F.col(c) for c in {in_df}.columns]")
        if lkp_col_exprs:
            lkp_cols_str = ", ".join(lkp_col_exprs)
            s.emit(f"    + [{lkp_cols_str}]")
        s.emit(f")")

    # ------------------------------------------------------------------
    # Router
    # ------------------------------------------------------------------

    def _build_router(self, node: PipelineNode, t: TransformationDef) -> None:
        g = self.graph
        s = self.script
        upstream = g.primary_upstream(node.instance_name)
        in_df = self._resolve_in_df(node.instance_name, upstream)

        s.section(f"ROUTER: {node.instance_name}  ({len(t.router_groups)} groups)")

        for grp in t.router_groups:
            grp_var = f"{g.df_var(node.instance_name)}_{_safe_var(grp.name)}"
            self._node_output[f"{node.instance_name}.{grp.name}"] = grp_var

            if not grp.condition:  # DEFAULT group
                s.emit(f"# Router group: {grp.name} (DEFAULT — catches all unmatched rows)")
                # Build NOT of all other conditions
                other_conds = [
                    g2.condition for g2 in t.router_groups
                    if g2.condition and g2.name != grp.name
                ]
                if other_conds:
                    negated = " | ".join(f"({translate_filter(c).pyspark_expr})" for c in other_conds)
                    s.emit(f"{grp_var} = {in_df}.filter(~({negated}))")
                else:
                    s.emit(f"{grp_var} = {in_df}")
            else:
                result = translate_filter(grp.condition)
                if result.confidence == Confidence.LOW:
                    s.warn(f"Low-confidence router condition for group {grp.name}: {grp.condition!r}")
                s.emit(f"# Router group: {grp.name}")
                s.emit(f"# PC condition: {grp.condition}")
                s.emit(f"{grp_var} = {in_df}.filter({result.pyspark_expr})")

            s.emit("")

        # Build group name → df var mapping for wiring
        group_name_to_var = {
            grp.name: f"{g.df_var(node.instance_name)}_{_safe_var(grp.name)}"
            for grp in t.router_groups
        }

        # Wire each direct successor to the correct group DataFrame.
        # PC Router connectors carry the group output port name as from_field,
        # which matches the RouterGroupDef.name.
        for edge in g.fields_flowing_out_of(node.instance_name):
            matched_var = group_name_to_var.get(edge.from_field)
            if matched_var and edge.to_node not in self._node_group_wiring:
                self._node_group_wiring[edge.to_node] = matched_var

        # Fallback: set base key to first group so any unmatched successor
        # gets a usable (if possibly wrong) DataFrame rather than df_UNKNOWN.
        if t.router_groups:
            self._node_output[node.instance_name] = (
                g.df_var(node.instance_name) + "_" + _safe_var(t.router_groups[0].name)
            )

    # ------------------------------------------------------------------
    # Update Strategy
    # ------------------------------------------------------------------

    def _build_update_strategy(self, node: PipelineNode, t: TransformationDef) -> None:
        g = self.graph
        s = self.script
        upstream = g.primary_upstream(node.instance_name)
        in_df = self._resolve_in_df(node.instance_name, upstream)
        out_df = g.df_var(node.instance_name)
        self._node_output[node.instance_name] = out_df

        strategy_expr = t.attributes.get("Update Strategy Expression", "DD_INSERT")
        s.section(f"UPDATE STRATEGY: {node.instance_name}")
        s.emit(f"# PC Update Strategy Expression: {strategy_expr}")
        s.emit(f"# DD_INSERT=0, DD_UPDATE=1, DD_DELETE=2, DD_REJECT=3")

        # Detect which operations are present in the strategy expression
        expr_upper = strategy_expr.upper()
        has_insert  = "DD_INSERT"  in expr_upper
        has_update  = "DD_UPDATE"  in expr_upper
        has_delete  = "DD_DELETE"  in expr_upper
        has_reject  = "DD_REJECT"  in expr_upper
        has_iif     = "IIF("       in expr_upper or "IF(" in expr_upper

        if not has_iif:
            # Constant-only expression (e.g. "DD_INSERT", "DD_UPDATE")
            flag_val = "0"
            if has_update:
                flag_val = "1"
            elif has_delete:
                flag_val = "2"
            elif has_reject:
                flag_val = "3"
            s.emit(f"{out_df} = {in_df}.withColumn('_update_flag', F.lit({flag_val}))")
        else:
            # Translate the PC IIF/DECODE expression to a PySpark CASE WHEN
            from .expr_translator import translate
            result = translate(strategy_expr)
            if result.confidence == Confidence.LOW:
                s.warn(
                    f"Low-confidence translation of Update Strategy expression: {strategy_expr!r}"
                )
                s.emit(f"# PC expression: {strategy_expr}")
                s.emit(f"# Translated: {result.pyspark_expr}")
            s.emit(f"# Add _update_flag column: 0=INSERT, 1=UPDATE, 2=DELETE, 3=REJECT")
            s.emit(f"{out_df} = {in_df}.withColumn('_update_flag', {result.pyspark_expr})")

        # Split into per-operation DataFrames for target write
        s.emit(f"")
        s.emit(f"# Split by operation type")
        s.emit(f"df_{_safe_var(node.instance_name)}_insert = {out_df}.filter(F.col('_update_flag') == 0)")
        s.emit(f"df_{_safe_var(node.instance_name)}_update = {out_df}.filter(F.col('_update_flag') == 1)")
        s.emit(f"df_{_safe_var(node.instance_name)}_delete = {out_df}.filter(F.col('_update_flag') == 2)")
        s.emit(f"df_{_safe_var(node.instance_name)}_reject = {out_df}.filter(F.col('_update_flag') == 3)")
        s.emit(f"# Use df_*_insert/.._update/.._delete/.._reject in the target write")
        s.emit(f"# INSERT: df.write.mode('append') or Delta merge whenNotMatchedInsertAll()")
        s.emit(f"# UPDATE: DeltaTable.merge().whenMatchedUpdateAll()")
        s.emit(f"# DELETE: DeltaTable.delete(condition)")
        s.emit(f"# REJECT: df.write to reject/error path")

    # ------------------------------------------------------------------
    # Sequence Generator
    # ------------------------------------------------------------------

    def _build_sequence_generator(self, node: PipelineNode, t: TransformationDef) -> None:
        g = self.graph
        s = self.script
        upstream = g.primary_upstream(node.instance_name)
        in_df = self._resolve_in_df(node.instance_name, upstream)
        out_df = g.df_var(node.instance_name)
        self._node_output[node.instance_name] = out_df

        next_val_port = next((p for p in t.ports if "NEXTVAL" in p.name.upper()), None)
        col_name = next_val_port.name if next_val_port else "SEQ_ID"

        s.section(f"SEQUENCE GENERATOR: {node.instance_name}")
        s.emit(f"# PC Sequence Generator → monotonically_increasing_id()")
        s.emit(f"# NOTE: IDs are unique per Spark job run but NOT sequential integers.")
        s.emit(f"# If you need true sequential IDs, use row_number() with an ORDER BY.")
        s.emit(f"{out_df} = {in_df}.withColumn(")
        s.emit(f'    "{col_name}",')
        s.emit(f"    F.monotonically_increasing_id(),")
        s.emit(f")")

    # ------------------------------------------------------------------
    # Sorter
    # ------------------------------------------------------------------

    def _build_sorter(self, node: PipelineNode, t: TransformationDef) -> None:
        g = self.graph
        s = self.script
        upstream = g.primary_upstream(node.instance_name)
        in_df = self._resolve_in_df(node.instance_name, upstream)
        out_df = g.df_var(node.instance_name)
        self._node_output[node.instance_name] = out_df

        # Sorter ports: INPUT/OUTPUT ports, sort direction in attributes
        sort_cols: List[str] = []
        for port in t.ports:
            if port.port_type == "INPUT/OUTPUT":
                direction = t.attributes.get(f"Direction for {port.name}", "ASCENDING")
                if direction.upper() == "DESCENDING":
                    sort_cols.append(f'F.col("{port.name}").desc()')
                else:
                    sort_cols.append(f'F.col("{port.name}")')

        s.section(f"SORTER: {node.instance_name}")
        if sort_cols:
            cols_str = ", ".join(sort_cols)
            s.emit(f"# NOTE: In Spark, orderBy has no performance benefit unless writing")
            s.emit(f"# to a sorted file format. Evaluate if this sort is truly needed.")
            s.emit(f"{out_df} = {in_df}.orderBy({cols_str})")
        else:
            s.todo(f"No sort columns detected in {node.instance_name} — add orderBy columns")
            s.emit(f"{out_df} = {in_df}")

    # ------------------------------------------------------------------
    # Normalizer
    # ------------------------------------------------------------------

    def _build_normalizer(self, node: PipelineNode, t: TransformationDef) -> None:
        g = self.graph
        s = self.script
        upstream = g.primary_upstream(node.instance_name)
        in_df = self._resolve_in_df(node.instance_name, upstream)
        out_df = g.df_var(node.instance_name)
        self._node_output[node.instance_name] = out_df

        s.section(f"NORMALIZER: {node.instance_name}")

        # Group OUTPUT ports by their REF_SOURCE_FIELD attribute.
        # Each group represents one "occurrence" column (e.g. item_1, item_2, item_3).
        # Pass-through (non-repeated) ports have an empty REF_SOURCE_FIELD.
        from collections import defaultdict
        groups: dict = defaultdict(list)
        passthrough_cols: list = []

        for port in t.ports:
            if "OUTPUT" not in port.port_type.upper():
                continue
            if port.ref_source_field:
                groups[port.ref_source_field].append(port.name)
            else:
                passthrough_cols.append(port.name)

        if not groups:
            # No REF_SOURCE_FIELD metadata — fall back to a generic stub
            s.warn(
                f"NORMALIZER {node.instance_name}: no REF_SOURCE_FIELD metadata found. "
                "Inspect source column structure and implement manually."
            )
            s.emit(f"# Use F.explode(F.array(...)) for repeated column groups")
            s.emit(f"{out_df} = {in_df}  # TODO: implement NORMALIZER logic")
            return

        # Emit F.array([F.struct(...)]) + F.explode for each group
        passthrough_str = (
            "F.col(" + "), F.col(".join(f'"{c}"' for c in passthrough_cols) + ")"
            if passthrough_cols else ""
        )

        s.emit(f"# NORMALIZER: transpose repeated column groups into rows")
        for group_key, cols in groups.items():
            s.emit(f"# Group '{group_key}': columns {cols}")

        if len(groups) == 1:
            group_key, cols = next(iter(groups.items()))
            # One struct per occurrence column — each becomes its own row after explode.
            # E.g. ITEM_1, ITEM_2, ITEM_3 → 3 rows, field named by group_key.
            array_elements = ", ".join(
                f'F.struct(F.col("{c}").alias("{group_key}"))' for c in cols
            )
            s.emit(f"# One struct per occurrence column so explode yields one row per occurrence")
            s.emit(f'{out_df} = {in_df}.select(')
            if passthrough_cols:
                pt_cols = ", ".join(f'F.col("{c}")' for c in passthrough_cols)
                s.emit(f'    {pt_cols},')
            s.emit(f'    F.explode(F.array({array_elements})).alias("_norm"),')
            s.emit(f').select(')
            if passthrough_cols:
                s.emit(f'    {pt_cols},')
            s.emit(f'    F.col("_norm.{group_key}").alias("{group_key}"),')
            s.emit(f')')
        else:
            # Multiple groups — needs a cross-product explode; emit skeleton
            s.warn(
                f"NORMALIZER {node.instance_name} has {len(groups)} groups — "
                "multi-group normalization requires manual wiring."
            )
            for group_key, cols in groups.items():
                s.emit(f'# Group {group_key!r}: {cols}')
            s.emit(f'{out_df} = {in_df}  # TODO: implement multi-group NORMALIZER')

    # ------------------------------------------------------------------
    # Target
    # ------------------------------------------------------------------

    def _build_target(self, node: PipelineNode) -> None:
        g = self.graph
        s = self.script
        upstream = g.primary_upstream(node.instance_name)
        in_df = self._resolve_in_df(node.instance_name, upstream)

        tgt_def = self.folder.targets.get(node.transformation_name)
        db_type = tgt_def.db_type if tgt_def else "Unknown"
        db_name = tgt_def.db_name if tgt_def else ""
        owner = (tgt_def.owner + ".") if (tgt_def and tgt_def.owner) else ""
        tgt_name = node.transformation_name

        # Select only the columns that the mapping writes to this target
        out_fields = g.output_fields(upstream) if upstream else []

        s.section(f"TARGET: {tgt_name}  ({db_type} / {db_name})")
        s.emit(f"logger.info('Writing target: {tgt_name}')")

        if out_fields:
            col_list = ", ".join(f'F.col("{c}")' for c in out_fields)
            s.emit(f"df_output_{_safe_var(tgt_name)} = {in_df}.select({col_list})")
            write_df = f"df_output_{_safe_var(tgt_name)}"
        else:
            write_df = in_df

        if db_type.upper() == "FLAT FILE":
            self._build_flat_file_target(node, tgt_def, tgt_name, write_df)
        elif _is_lakehouse(db_type):
            self._build_lakehouse_target(node, tgt_def, write_df, db_type)
        else:
            self._build_jdbc_target(node, tgt_def, tgt_name, owner, write_df, db_type)

    def _build_flat_file_target(
        self, node: PipelineNode, tgt_def: Optional[TargetDef],
        tgt_name: str, write_df: str,
    ) -> None:
        s = self.script
        delim = (tgt_def.delimiter if tgt_def and tgt_def.delimiter else ",")
        path_arg = _arg_name(f"S3_OUTPUT_PATH_{_safe_var(tgt_name)}")
        s.add_arg(path_arg)
        s.emit(f"# Writing FLAT FILE target: {tgt_name}")
        s.emit(f"({write_df}.write")
        s.emit(f'    .format("csv")')
        s.emit(f'    .option("header", "true")')
        s.emit(f'    .option("sep", "{delim}")')
        s.emit(f'    .mode("overwrite")')
        s.emit(f'    .save(args["{path_arg}"]))')

    def _has_upstream_update_strategy(self, node_name: str) -> bool:
        """Return True if any node upstream of node_name is an Update Strategy transformation."""
        visited: Set[str] = set()
        queue = list(self.graph.all_upstream_names(node_name))
        while queue:
            n = queue.pop()
            if n in visited:
                continue
            visited.add(n)
            nd = self.graph.nodes.get(n)
            if nd and nd.transformation_def and nd.transformation_def.type == TransformationType.UPDATE_STRATEGY:
                return True
            queue.extend(self.graph.all_upstream_names(n))
        return False

    def _build_jdbc_target(
        self, node: PipelineNode, tgt_def: Optional[TargetDef],
        tgt_name: str, owner: str, write_df: str, db_type: str,
    ) -> None:
        s = self.script
        conn_key = (tgt_def.db_name if tgt_def and tgt_def.db_name else tgt_name)
        conn_arg = _arg_name(f"CONN_TGT_{conn_key}")
        s.add_arg(conn_arg)
        table_ref = f"{owner}{tgt_name}"

        has_us = self._has_upstream_update_strategy(node.instance_name)
        if has_us:
            s.warn(
                f"Target '{tgt_name}' has an upstream Update Strategy — simple overwrite will "
                "truncate the table. Use the _insert/_update/_delete DataFrames from the Update "
                "Strategy section and implement a Delta merge or JDBC upsert instead."
            )
            write_mode = '"append"  # WARNING: upstream Update Strategy detected — see above'
        else:
            write_mode = '"overwrite"  # TODO: change to "append" as needed'

        conn_var = f"_conn_tgt_{_safe_var(conn_key)}"
        s.emit(f'{conn_var} = glueContext.extract_jdbc_conf(args["{conn_arg}"])')
        s.emit(f"({write_df}.write")
        s.emit(f'    .format("jdbc")')
        s.emit(f'    .option("url", {conn_var}["url"])')
        s.emit(f'    .option("dbtable", "{table_ref}")')
        s.emit(f'    .option("user", {conn_var}["user"])')
        s.emit(f'    .option("password", {conn_var}["password"])')
        s.emit(f'    .mode({write_mode})')
        s.emit(f"    .save()")
        s.emit(f")")

    def _build_lakehouse_target(
        self, node: PipelineNode, tgt_def: Optional[TargetDef],
        write_df: str, db_type: str,
    ) -> None:
        s = self.script
        s.add_arg("S3_OUTPUT_PATH")
        db_type_lower = db_type.lower()

        if "delta" in db_type_lower:
            s.emit(f"# Writing to Delta Lake")
            s.emit(f"({write_df}.write")
            s.emit(f'    .format("delta")')
            s.emit(f'    .mode("overwrite")   # TODO: change to "append" or "merge" as needed')
            s.emit(f'    .save(args["S3_OUTPUT_PATH"]))')
        else:
            fmt = "parquet"
            if "orc" in db_type_lower:
                fmt = "orc"
            s.emit(f"# Writing to S3 as {fmt.upper()}")
            s.emit(f"({write_df}.write")
            s.emit(f'    .format("{fmt}")')
            s.emit(f'    .mode("overwrite")')
            s.emit(f'    .option("compression", "snappy")')
            s.emit(f'    .save(args["S3_OUTPUT_PATH"]))')

    # ------------------------------------------------------------------
    # Dispatch
    # ------------------------------------------------------------------

    def _dispatch_transformation(self, node: PipelineNode, t: TransformationDef) -> None:
        dispatch = {
            TransformationType.EXPRESSION:          self._build_expression,
            TransformationType.FILTER:              self._build_filter,
            TransformationType.AGGREGATOR:          self._build_aggregator,
            TransformationType.JOINER:              self._build_joiner,
            TransformationType.LOOKUP:              self._build_lookup,
            TransformationType.ROUTER:              self._build_router,
            TransformationType.UPDATE_STRATEGY:     self._build_update_strategy,
            TransformationType.SEQUENCE_GENERATOR:  self._build_sequence_generator,
            TransformationType.SORTER:              self._build_sorter,
            TransformationType.NORMALIZER:          self._build_normalizer,
        }
        handler = dispatch.get(t.type)
        if handler:
            handler(node, t)
        else:
            g = self.graph
            upstream = g.primary_upstream(node.instance_name)
            in_df = self._resolve_in_df(node.instance_name, upstream)
            out_df = g.df_var(node.instance_name)
            self._node_output[node.instance_name] = out_df
            self.script.todo(
                f"Unsupported transformation type '{t.type.value}' on '{node.instance_name}' "
                "— translate manually"
            )
            self.script.emit(f"{out_df} = {in_df}  # passthrough — review above TODO")


# ---------------------------------------------------------------------------
# Public function
# ---------------------------------------------------------------------------

def build_glue_script(mapping: MappingDef, folder: FolderDef) -> Tuple[str, List[str]]:
    """
    Generate a Glue PySpark script for the given mapping.
    Returns (script_text, list_of_warnings).
    """
    builder = GlueJobCodeBuilder(mapping, folder)
    return builder.build()
