"""
AWS Glue PySpark script builder.

Traverses the pipeline graph in topological order and emits idiomatic
PySpark code for each transformation type.

Supported transformations:
  SOURCE_QUALIFIER   — JDBC (SQL Server), FLAT FILE (delimited + fixed-width), Excel
  EXPRESSION         — withColumn() calls, translated via expr_translator
  FILTER             — df.filter() with translated condition
  AGGREGATOR         — groupBy() + agg()
  JOINER             — df.join() with translated condition
  LOOKUP             — broadcast join
  ROUTER             — df.filter() fan-out into multiple DataFrames
  UPDATE_STRATEGY    — insertInto / merge stub with TODO
  SEQUENCE_GENERATOR — monotonically_increasing_id()
  SORTER             — df.orderBy()
  NORMALIZER         — explode() stub with TODO (complex, needs manual review)
  TARGET             — JDBC write, S3 Parquet/Delta write

HIPAA note: generated scripts include a logging guard that prevents
column values from appearing in log output. Column names are logged
at INFO level but values only at DEBUG (which should be disabled in prod).
"""

from __future__ import annotations
import textwrap
from datetime import datetime, timezone
from typing import Dict, List, Optional, Tuple

from pc_extractor.models import (
    FolderDef, MappingDef, SourceDef, TargetDef, TransformationDef,
    TransformationType,
)
from .graph import PipelineGraph, PipelineNode
from .expr_translator import translate, translate_filter, translate_join_condition, Confidence


# ---------------------------------------------------------------------------
# JDBC connection type mapping (PC db type → Glue connection_type)
# ---------------------------------------------------------------------------

_JDBC_CONN_TYPE = {
    "microsoft sql server": "sqlserver",
    "sql server":           "sqlserver",
    "oracle":               "oracle",
    "mysql":                "mysql",
    "mariadb":              "mysql",
    "postgresql":           "postgresql",
    "redshift":             "redshift",
    "db2":                  "db2",
    "teradata":             "teradata",
    "snowflake":            "custom",   # Snowflake uses JDBC option
}

_LAKEHOUSE_TYPES = {"delta", "s3", "parquet", "orc", "iceberg", "glue catalog"}


def _glue_conn_type(db_type: str) -> str:
    return _JDBC_CONN_TYPE.get(db_type.lower(), "jdbc")


def _is_lakehouse(db_type: str) -> bool:
    return db_type.lower() in _LAKEHOUSE_TYPES


def _safe_var(name: str) -> str:
    """Convert any string to a safe Python identifier."""
    import re
    return re.sub(r"[^a-z0-9_]", "_", name.lower()).strip("_")


def _arg_name(connection_hint: str) -> str:
    """Glue job arg name for a connection (uppercase, no spaces)."""
    return _safe_var(connection_hint).upper()


# ---------------------------------------------------------------------------
# Script sections builder
# ---------------------------------------------------------------------------

class GlueScriptBuilder:
    """Accumulates code sections and renders the final script."""

    def __init__(self, mapping_name: str, folder_name: str) -> None:
        self.mapping_name = mapping_name
        self.folder_name = folder_name
        self._imports: List[str] = []
        self._args: List[str] = []             # getResolvedOptions arg names
        self._body: List[str] = []             # main job body lines
        self._warnings: List[str] = []

    # -- public helpers --

    def add_arg(self, arg: str) -> None:
        if arg not in self._args:
            self._args.append(arg)

    def add_import(self, imp: str) -> None:
        if imp not in self._imports:
            self._imports.append(imp)

    def emit(self, *lines: str) -> None:
        self._body.extend(lines)

    def warn(self, msg: str) -> None:
        self._warnings.append(msg)
        self._body.append(f"# WARNING: {msg}")

    def todo(self, msg: str) -> None:
        self._body.append(f"# TODO: {msg}")

    def section(self, title: str) -> None:
        self._body.append("")
        self._body.append(f"# {'=' * 58}")
        self._body.append(f"# {title}")
        self._body.append(f"# {'=' * 58}")

    # -- render --

    def render(self, score: int, platform: str) -> str:
        ts = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
        warnings_block = ""
        if self._warnings:
            warnings_block = "\n# WARNINGS:\n" + "\n".join(f"#   {w}" for w in self._warnings) + "\n"

        extra_imports = ""
        if self._imports:
            extra_imports = "\n" + "\n".join(self._imports)

        args_list = ",\n    ".join(f"'{a}'" for a in self._args)

        body = "\n".join(self._body)

        return textwrap.dedent(f"""\
            # =============================================================
            # Generated by pc-extractor glue-gen
            # Source mapping : {self.mapping_name}
            # Folder         : {self.folder_name}
            # Complexity score: {score}  |  Platform: {platform}
            # Generated      : {ts}
            # REVIEW REQUIRED: See any TODO/WARNING comments below
            # =============================================================
            # HIPAA NOTE: This job may process regulated data.
            #   - Do NOT log column values at INFO level.
            #   - Enable Glue job bookmarks to avoid reprocessing.
            #   - Ensure the Glue connection uses SSL/TLS.
            #   - Validate IAM role has least-privilege S3/RDS access.
            # =============================================================
            {warnings_block}
            import sys{extra_imports}
            from awsglue.transforms import *
            from awsglue.utils import getResolvedOptions
            from pyspark.context import SparkContext
            from awsglue.context import GlueContext
            from awsglue.job import Job
            from awsglue.dynamicframe import DynamicFrame
            from pyspark.sql import functions as F
            from pyspark.sql.types import *
            import logging

            logger = logging.getLogger()
            logger.setLevel(logging.INFO)

            # --- Job parameters ---
            args = getResolvedOptions(sys.argv, [
                'JOB_NAME',
                {args_list},
            ])

            sc = SparkContext()
            glueContext = GlueContext(sc)
            spark = glueContext.spark_session
            job = Job(glueContext)
            job.init(args['JOB_NAME'], args)

            {body}

            job.commit()
            logger.info("Job %s completed successfully", args['JOB_NAME'])
        """)


# ---------------------------------------------------------------------------
# Main code builder
# ---------------------------------------------------------------------------

class GlueJobCodeBuilder:

    def __init__(
        self,
        mapping: MappingDef,
        folder: FolderDef,
    ) -> None:
        self.mapping = mapping
        self.folder = folder
        # Build transformation lookup from mapping
        self._xform_lookup: Dict[str, TransformationDef] = {
            t.name: t for t in mapping.transformations
        }
        self.graph = PipelineGraph.from_mapping(mapping, self._xform_lookup)
        self.script = GlueScriptBuilder(mapping.name, mapping.folder)
        # Track which df var name each node produces
        self._node_output: Dict[str, str] = {}

    def build(self) -> Tuple[str, List[str]]:
        """
        Build the Glue PySpark script.
        Returns (script_text, warnings_list).
        """
        g = self.graph
        s = self.script

        # Collect job parameters from mapping variables
        for var in self.mapping.variables:
            if var.is_param:
                arg = _arg_name(var.name.lstrip("$"))
                s.add_arg(arg)

        # Walk the pipeline in topological order
        for node in g.topological_order():
            if g.is_source_instance(node):
                # Raw source nodes (SOURCE type) — data is read via their SQ
                continue

            if g.is_target(node):
                self._build_target(node)
            elif g.is_source_qualifier(node):
                self._build_source_qualifier(node)
            else:
                t_def = node.transformation_def
                if t_def is None:
                    s.warn(f"No transformation definition found for instance '{node.instance_name}'")
                    continue
                self._dispatch_transformation(node, t_def)

        score = self.mapping.complexity_score or 1
        platform = self.mapping.target_platform.value if self.mapping.target_platform else "GLUE"
        return s.render(score, platform), self.script._warnings

    # ------------------------------------------------------------------
    # Source Qualifier
    # ------------------------------------------------------------------

    def _build_source_qualifier(self, node: PipelineNode) -> None:
        g = self.graph
        s = self.script
        t = node.transformation_def
        df_var = g.df_var(node.instance_name)
        self._node_output[node.instance_name] = df_var

        # Find the source instance that feeds this SQ
        source_inst_names = [
            e.from_node for e in g.fields_flowing_into(node.instance_name)
        ]
        source_inst_name = source_inst_names[0] if source_inst_names else None
        source_node = g.nodes.get(source_inst_name) if source_inst_name else None
        src_def: Optional[SourceDef] = None

        if source_node:
            src_def = self.folder.sources.get(source_node.transformation_name)

        db_type = src_def.db_type if src_def else "Unknown"
        db_name = src_def.db_name if src_def else ""
        owner = (src_def.owner + ".") if (src_def and src_def.owner) else ""
        src_name = source_node.transformation_name if source_node else node.transformation_name

        s.section(
            f"SOURCE: {src_name}  ({db_type} / {db_name})\n"
            f"# PC Transformation: {node.instance_name}"
        )
        s.emit(f"logger.info('Reading source: {src_name}')")

        if db_type.upper() == "FLAT FILE":
            self._build_flat_file_source(node, src_def, df_var)
        elif db_type.upper() in ("EXCEL", "MICROSOFT EXCEL"):
            self._build_excel_source(node, src_def, df_var)
        elif _is_lakehouse(db_type):
            self._build_lakehouse_source(node, src_def, df_var)
        else:
            self._build_jdbc_source(node, src_def, src_name, owner, df_var, db_type)

        # Apply source filter if present
        if t and t.filter_condition:
            filt = translate_filter(t.filter_condition)
            if filt.confidence == Confidence.LOW:
                s.warn(f"Low-confidence filter translation on {node.instance_name}: {t.filter_condition!r}")
            s.emit("")
            s.emit(f"# Source filter: {t.filter_condition}")
            s.emit(f"{df_var} = {df_var}.filter({filt.pyspark_expr})")

        # Apply SQL override comment
        if t and t.sql_query:
            s.emit("")
            s.emit(f"# NOTE: Original PC mapping used a SQL override on {node.instance_name}.")
            s.emit(f"# The query below is the original — the JDBC read above reads the full")
            s.emit(f"# table; add .filter()/.select() calls to replicate the SQL logic.")
            s.emit(f"# Original SQL:")
            for line in t.sql_query.splitlines():
                s.emit(f"#   {line}")
            s.warn(f"SQL override on {node.instance_name} — incorporate query logic into filter/select")

    def _build_jdbc_source(
        self, node: PipelineNode, src_def: Optional[SourceDef],
        src_name: str, owner: str, df_var: str, db_type: str,
    ) -> None:
        s = self.script
        conn_arg = _arg_name(f"CONN_{src_name}")
        s.add_arg(conn_arg)
        conn_type = _glue_conn_type(db_type)
        table_ref = f"{owner}{src_name}"

        s.emit(f"{df_var} = glueContext.create_dynamic_frame.from_options(")
        s.emit(f'    connection_type="{conn_type}",')
        s.emit(f"    connection_options={{")
        s.emit(f'        "useConnectionProperties": "true",')
        s.emit(f'        "dbtable": "{table_ref}",')
        s.emit(f'        "connectionName": args["{conn_arg}"],')
        s.emit(f"    }},")
        s.emit(f").toDF()")

    def _build_flat_file_source(
        self, node: PipelineNode, src_def: Optional[SourceDef], df_var: str
    ) -> None:
        s = self.script
        s.add_arg("S3_INPUT_PATH")

        if src_def and src_def.is_fixed_width:
            self._build_fixed_width_source(node, src_def, df_var)
        else:
            delim = src_def.delimiter if (src_def and src_def.delimiter) else ","
            s.emit(f"{df_var} = spark.read \\")
            s.emit(f'    .option("header", "true") \\')
            s.emit(f'    .option("sep", "{delim}") \\')
            s.emit(f'    .option("inferSchema", "false") \\')
            if src_def and src_def.fields:
                schema_lines = self._build_schema(src_def)
                s.emit(f"    .schema(StructType([")
                for sl in schema_lines:
                    s.emit(f"        {sl}")
                s.emit(f"    ])) \\")
            s.emit(f'    .csv(args["S3_INPUT_PATH"])')

    def _build_fixed_width_source(
        self, node: PipelineNode, src_def: SourceDef, df_var: str
    ) -> None:
        s = self.script
        s.add_import("import re as _re")
        s.emit(f"# Fixed-width file — reading as text then splitting by position")

        if not src_def.fields:
            s.warn(f"Fixed-width source {src_def.name} has no field definitions — cannot determine column positions")
            s.emit(f"{df_var} = spark.read.text(args['S3_INPUT_PATH'])")
            return

        # Generate field position parsing code
        # PowerCenter fixed-width uses LENGTH to determine positions
        positions: List[Tuple[str, int, int]] = []
        pos = 0
        for f in src_def.fields:
            length = f.length or f.precision or 10
            positions.append((f.name, pos, pos + length))
            pos += length

        s.emit(f"_raw_{_safe_var(src_def.name)} = spark.read.text(args['S3_INPUT_PATH'])")
        s.emit(f"{df_var} = _raw_{_safe_var(src_def.name)}.select(")
        for fname, start, end in positions:
            s.emit(f'    F.substring(F.col("value"), {start + 1}, {end - start}).alias("{fname}"),')
        s.emit(f")")

    def _build_excel_source(
        self, node: PipelineNode, src_def: Optional[SourceDef], df_var: str
    ) -> None:
        s = self.script
        s.add_import("import pandas as _pd")
        s.add_arg("S3_INPUT_PATH")
        s.add_arg("EXCEL_SHEET_NAME")
        src_name = src_def.name if src_def else node.transformation_name

        s.emit(f"# Excel source — read via pandas then convert to Spark DataFrame")
        s.emit(f"# NOTE: For large Excel files consider converting to CSV/Parquet upstream")
        s.emit(f"_pdf_{_safe_var(src_name)} = _pd.read_excel(")
        s.emit(f'    args["S3_INPUT_PATH"],')
        s.emit(f'    sheet_name=args["EXCEL_SHEET_NAME"],')
        s.emit(f"    dtype=str,   # read all as string, cast below")
        s.emit(f")")
        s.emit(f"{df_var} = spark.createDataFrame(_pdf_{_safe_var(src_name)})")

    def _build_lakehouse_source(
        self, node: PipelineNode, src_def: Optional[SourceDef], df_var: str
    ) -> None:
        s = self.script
        s.add_arg("S3_INPUT_PATH")
        db_type = src_def.db_type.lower() if src_def else "parquet"
        fmt = "delta" if "delta" in db_type else "parquet"
        s.emit(f'{df_var} = spark.read.format("{fmt}").load(args["S3_INPUT_PATH"])')

    def _build_schema(self, src_def: SourceDef) -> List[str]:
        """Generate StructType field lines for a source definition."""
        _type_map = {
            "int": "IntegerType()", "integer": "IntegerType()",
            "bigint": "LongType()", "smallint": "ShortType()",
            "tinyint": "ByteType()",
            "decimal": "DecimalType({precision}, {scale})",
            "numeric": "DecimalType({precision}, {scale})",
            "float": "DoubleType()", "double": "DoubleType()",
            "real": "FloatType()",
            "varchar": "StringType()", "nvarchar": "StringType()",
            "char": "StringType()", "nchar": "StringType()",
            "string": "StringType()", "text": "StringType()",
            "date": "DateType()",
            "datetime": "TimestampType()", "datetime2": "TimestampType()",
            "timestamp": "TimestampType()",
            "bit": "BooleanType()", "boolean": "BooleanType()",
            "binary": "BinaryType()", "varbinary": "BinaryType()",
        }
        lines = []
        for f in src_def.fields:
            dt = f.datatype.lower()
            spark_type = _type_map.get(dt, "StringType()")
            if "{precision}" in spark_type:
                spark_type = spark_type.format(precision=f.precision or 18, scale=f.scale or 2)
            nullable = "True" if f.nullable else "False"
            lines.append(f'StructField("{f.name}", {spark_type}, {nullable}),')
        return lines

    # ------------------------------------------------------------------
    # Expression
    # ------------------------------------------------------------------

    def _build_expression(self, node: PipelineNode, t: TransformationDef) -> None:
        g = self.graph
        s = self.script
        upstream = g.primary_upstream(node.instance_name)
        in_df = self._node_output.get(upstream, "df_UNKNOWN") if upstream else "df_UNKNOWN"
        out_df = g.df_var(node.instance_name)
        self._node_output[node.instance_name] = out_df

        s.section(f"EXPRESSION: {node.instance_name}")
        s.emit(f"logger.info('Applying expressions: {node.instance_name}')")
        s.emit(f"{out_df} = {in_df}")

        # Only emit withColumn for OUTPUT ports that have a non-trivial expression
        for port in t.ports:
            if port.port_type not in ("OUTPUT", "INPUT/OUTPUT"):
                continue
            expr = port.expression.strip() if port.expression else ""
            if not expr or expr == port.name:
                continue   # pass-through, no withColumn needed
            result = translate(expr)
            if result.confidence == Confidence.LOW:
                s.warn(
                    f"Low-confidence expression translation for port {port.name} "
                    f"in {node.instance_name}: {expr!r}"
                )
                s.emit(f"# TODO: Verify translation of: {expr}")
            s.emit(
                f"{out_df} = {out_df}.withColumn("
                f'"{port.name}", {result.pyspark_expr})'
            )

    # ------------------------------------------------------------------
    # Filter
    # ------------------------------------------------------------------

    def _build_filter(self, node: PipelineNode, t: TransformationDef) -> None:
        g = self.graph
        s = self.script
        upstream = g.primary_upstream(node.instance_name)
        in_df = self._node_output.get(upstream, "df_UNKNOWN") if upstream else "df_UNKNOWN"
        out_df = g.df_var(node.instance_name)
        self._node_output[node.instance_name] = out_df

        condition = t.filter_condition or t.attributes.get("Filter Condition", "")
        s.section(f"FILTER: {node.instance_name}")
        if condition:
            result = translate_filter(condition)
            if result.confidence == Confidence.LOW:
                s.warn(f"Low-confidence filter: {condition!r}")
            s.emit(f"# PC condition: {condition}")
            s.emit(f"{out_df} = {in_df}.filter({result.pyspark_expr})")
        else:
            s.todo(f"Filter condition not found for {node.instance_name} — add filter logic")
            s.emit(f"{out_df} = {in_df}  # TODO: add filter condition")

    # ------------------------------------------------------------------
    # Aggregator
    # ------------------------------------------------------------------

    def _build_aggregator(self, node: PipelineNode, t: TransformationDef) -> None:
        g = self.graph
        s = self.script
        upstream = g.primary_upstream(node.instance_name)
        in_df = self._node_output.get(upstream, "df_UNKNOWN") if upstream else "df_UNKNOWN"
        out_df = g.df_var(node.instance_name)
        self._node_output[node.instance_name] = out_df

        s.section(f"AGGREGATOR: {node.instance_name}")

        # Separate group-by ports (INPUT/OUTPUT, no aggregate expression)
        # from aggregate ports (OUTPUT with SUM/COUNT/AVG/etc.)
        groupby_cols: List[str] = []
        agg_exprs: List[str] = []

        for port in t.ports:
            expr = (port.expression or "").strip()
            has_agg = any(
                fn in expr.upper()
                for fn in ("SUM(", "COUNT(", "AVG(", "MIN(", "MAX(", "FIRST(", "LAST(", "MEDIAN(")
            )
            if port.port_type == "INPUT/OUTPUT" and not has_agg:
                groupby_cols.append(f'"{port.name}"')
            elif port.port_type == "OUTPUT" and has_agg:
                result = translate(expr)
                if result.confidence == Confidence.LOW:
                    s.warn(f"Low-confidence agg expression for {port.name}: {expr!r}")
                agg_exprs.append(
                    f"{result.pyspark_expr}.alias(\"{port.name}\")"
                )

        if groupby_cols:
            gb = ", ".join(groupby_cols)
            if agg_exprs:
                agg = ",\n        ".join(agg_exprs)
                s.emit(f"logger.info('Aggregating: {node.instance_name}')")
                s.emit(f"{out_df} = {in_df}.groupBy({gb}).agg(")
                s.emit(f"    {agg},")
                s.emit(f")")
            else:
                s.todo(f"No aggregate expressions found in {node.instance_name}")
                s.emit(f"{out_df} = {in_df}.groupBy({gb}).count()")
        else:
            # Global aggregation
            if agg_exprs:
                agg = ",\n    ".join(agg_exprs)
                s.emit(f"{out_df} = {in_df}.agg({agg})")
            else:
                s.todo(f"Empty aggregator {node.instance_name} — add groupBy/agg logic")
                s.emit(f"{out_df} = {in_df}")

    # ------------------------------------------------------------------
    # Joiner
    # ------------------------------------------------------------------

    def _build_joiner(self, node: PipelineNode, t: TransformationDef) -> None:
        g = self.graph
        s = self.script
        all_upstream = g.all_upstream_names(node.instance_name)
        out_df = g.df_var(node.instance_name)
        self._node_output[node.instance_name] = out_df

        if len(all_upstream) < 2:
            s.warn(f"JOINER {node.instance_name} has fewer than 2 inputs — check connector definitions")
            left_df = self._node_output.get(all_upstream[0], "df_UNKNOWN") if all_upstream else "df_UNKNOWN"
            s.emit(f"{out_df} = {left_df}  # TODO: add second input to join")
            return

        left_df  = self._node_output.get(all_upstream[0], "df_left")
        right_df = self._node_output.get(all_upstream[1], "df_right")

        # Determine join type
        join_type_map = {
            "normal join":        "inner",
            "master outer join":  "left",
            "detail outer join":  "right",
            "full outer join":    "outer",
        }
        pc_join_type = (t.join_type or "Normal Join").lower()
        spark_join_type = join_type_map.get(pc_join_type, "inner")

        join_cond = t.join_condition or ""
        cond_result = translate_join_condition(join_cond)

        s.section(
            f"JOINER: {node.instance_name}\n"
            f"# Join type: {t.join_type or 'Normal'}  |  Condition: {join_cond}"
        )
        if cond_result.notes:
            for note in cond_result.notes:
                s.emit(f"# NOTE: {note}")

        s.emit(f"logger.info('Joining: {node.instance_name}')")
        s.emit(f"{out_df} = {left_df}.join(")
        s.emit(f"    {right_df},")
        s.emit(f"    on={cond_result.pyspark_expr},")
        s.emit(f'    how="{spark_join_type}",')
        s.emit(f")")

    # ------------------------------------------------------------------
    # Lookup
    # ------------------------------------------------------------------

    def _build_lookup(self, node: PipelineNode, t: TransformationDef) -> None:
        g = self.graph
        s = self.script
        upstream = g.primary_upstream(node.instance_name)
        in_df = self._node_output.get(upstream, "df_UNKNOWN") if upstream else "df_UNKNOWN"
        out_df = g.df_var(node.instance_name)
        self._node_output[node.instance_name] = out_df

        lkp_table = t.attributes.get("Lookup Table Name", "UNKNOWN_LOOKUP_TABLE")
        lkp_conn_arg = _arg_name(f"CONN_LKP_{lkp_table}")
        s.add_arg(lkp_conn_arg)

        lkp_condition = t.lookup_condition or ""
        cond_result = translate_join_condition(lkp_condition)

        # Output ports from the lookup (LKP_ prefixed ports)
        lkp_output_ports = [
            p for p in t.ports
            if p.port_type in ("OUTPUT", "RETURN VALUE") and p.name.upper().startswith("LKP_")
        ]
        select_exprs = [f'"{p.name}"' for p in lkp_output_ports] if lkp_output_ports else ["*"]

        s.section(
            f"LOOKUP: {node.instance_name}\n"
            f"# Lookup table: {lkp_table}  |  Condition: {lkp_condition}"
        )
        s.emit(f"logger.info('Loading lookup table: {lkp_table}')")
        s.emit(f"df_lkp_{_safe_var(node.instance_name)} = glueContext.create_dynamic_frame.from_options(")
        s.emit(f'    connection_type="sqlserver",')
        s.emit(f"    connection_options={{")
        s.emit(f'        "useConnectionProperties": "true",')
        s.emit(f'        "dbtable": "{lkp_table}",')
        s.emit(f'        "connectionName": args["{lkp_conn_arg}"],')
        s.emit(f"    }},")
        s.emit(f").toDF()")
        s.emit(f"# Broadcast hint for small lookup tables")
        s.emit(f"df_lkp_{_safe_var(node.instance_name)} = F.broadcast(df_lkp_{_safe_var(node.instance_name)})")
        s.emit(f"")
        s.emit(f"{out_df} = {in_df}.join(")
        s.emit(f"    df_lkp_{_safe_var(node.instance_name)},")
        s.emit(f"    on={cond_result.pyspark_expr},")
        s.emit(f'    how="left",   # PC default: return null on no match')
        s.emit(f")")
        if lkp_output_ports:
            cols = " + ".join(
                f'[F.col("{p.name}")]' for p in lkp_output_ports
            )
            s.emit(f"# Select original columns plus lookup outputs")
            s.emit(f"# Adjust column list if there are naming conflicts")

    # ------------------------------------------------------------------
    # Router
    # ------------------------------------------------------------------

    def _build_router(self, node: PipelineNode, t: TransformationDef) -> None:
        g = self.graph
        s = self.script
        upstream = g.primary_upstream(node.instance_name)
        in_df = self._node_output.get(upstream, "df_UNKNOWN") if upstream else "df_UNKNOWN"

        s.section(f"ROUTER: {node.instance_name}  ({len(t.router_groups)} groups)")

        for grp in t.router_groups:
            grp_var = f"{g.df_var(node.instance_name)}_{_safe_var(grp.name)}"
            self._node_output[f"{node.instance_name}.{grp.name}"] = grp_var

            if not grp.condition:  # DEFAULT group
                s.emit(f"# Router group: {grp.name} (DEFAULT — catches all unmatched rows)")
                # Build NOT of all other conditions
                other_conds = [
                    g2.condition for g2 in t.router_groups
                    if g2.condition and g2.name != grp.name
                ]
                if other_conds:
                    negated = " | ".join(f"({translate_filter(c).pyspark_expr})" for c in other_conds)
                    s.emit(f"{grp_var} = {in_df}.filter(~({negated}))")
                else:
                    s.emit(f"{grp_var} = {in_df}")
            else:
                result = translate_filter(grp.condition)
                if result.confidence == Confidence.LOW:
                    s.warn(f"Low-confidence router condition for group {grp.name}: {grp.condition!r}")
                s.emit(f"# Router group: {grp.name}")
                s.emit(f"# PC condition: {grp.condition}")
                s.emit(f"{grp_var} = {in_df}.filter({result.pyspark_expr})")

            s.emit("")

        # Primary output (first group) for downstream nodes
        if t.router_groups:
            self._node_output[node.instance_name] = (
                g.df_var(node.instance_name) + "_" + _safe_var(t.router_groups[0].name)
            )

    # ------------------------------------------------------------------
    # Update Strategy
    # ------------------------------------------------------------------

    def _build_update_strategy(self, node: PipelineNode, t: TransformationDef) -> None:
        g = self.graph
        s = self.script
        upstream = g.primary_upstream(node.instance_name)
        in_df = self._node_output.get(upstream, "df_UNKNOWN") if upstream else "df_UNKNOWN"
        out_df = g.df_var(node.instance_name)
        self._node_output[node.instance_name] = out_df

        strategy_expr = t.attributes.get("Update Strategy Expression", "DD_INSERT")
        s.section(f"UPDATE STRATEGY: {node.instance_name}")
        s.emit(f"# PC Update Strategy Expression: {strategy_expr}")
        s.todo(
            f"Update Strategy '{strategy_expr}' — implement as Delta MERGE or "
            "target JDBC upsert. Example below uses a 'flag' column approach."
        )
        s.emit(f"# Common strategy values: DD_INSERT=0, DD_UPDATE=1, DD_DELETE=2, DD_REJECT=3")
        s.emit(f"# Add a column to flag the operation, then handle in the target write")
        s.emit(f"{out_df} = {in_df}.withColumn(")
        s.emit(f'    "_update_flag",')
        s.emit(f"    F.lit(0)  # TODO: translate strategy expression: {strategy_expr}")
        s.emit(f")")

    # ------------------------------------------------------------------
    # Sequence Generator
    # ------------------------------------------------------------------

    def _build_sequence_generator(self, node: PipelineNode, t: TransformationDef) -> None:
        g = self.graph
        s = self.script
        upstream = g.primary_upstream(node.instance_name)
        in_df = self._node_output.get(upstream, "df_UNKNOWN") if upstream else "df_UNKNOWN"
        out_df = g.df_var(node.instance_name)
        self._node_output[node.instance_name] = out_df

        next_val_port = next((p for p in t.ports if "NEXTVAL" in p.name.upper()), None)
        col_name = next_val_port.name if next_val_port else "SEQ_ID"

        s.section(f"SEQUENCE GENERATOR: {node.instance_name}")
        s.emit(f"# PC Sequence Generator → monotonically_increasing_id()")
        s.emit(f"# NOTE: IDs are unique per Spark job run but NOT sequential integers.")
        s.emit(f"# If you need true sequential IDs, use row_number() with an ORDER BY.")
        s.emit(f"{out_df} = {in_df}.withColumn(")
        s.emit(f'    "{col_name}",')
        s.emit(f"    F.monotonically_increasing_id(),")
        s.emit(f")")

    # ------------------------------------------------------------------
    # Sorter
    # ------------------------------------------------------------------

    def _build_sorter(self, node: PipelineNode, t: TransformationDef) -> None:
        g = self.graph
        s = self.script
        upstream = g.primary_upstream(node.instance_name)
        in_df = self._node_output.get(upstream, "df_UNKNOWN") if upstream else "df_UNKNOWN"
        out_df = g.df_var(node.instance_name)
        self._node_output[node.instance_name] = out_df

        # Sorter ports: INPUT/OUTPUT ports, sort direction in attributes
        sort_cols: List[str] = []
        for port in t.ports:
            if port.port_type == "INPUT/OUTPUT":
                direction = t.attributes.get(f"Direction for {port.name}", "ASCENDING")
                if direction.upper() == "DESCENDING":
                    sort_cols.append(f'F.col("{port.name}").desc()')
                else:
                    sort_cols.append(f'F.col("{port.name}")')

        s.section(f"SORTER: {node.instance_name}")
        if sort_cols:
            cols_str = ", ".join(sort_cols)
            s.emit(f"# NOTE: In Spark, orderBy has no performance benefit unless writing")
            s.emit(f"# to a sorted file format. Evaluate if this sort is truly needed.")
            s.emit(f"{out_df} = {in_df}.orderBy({cols_str})")
        else:
            s.todo(f"No sort columns detected in {node.instance_name} — add orderBy columns")
            s.emit(f"{out_df} = {in_df}")

    # ------------------------------------------------------------------
    # Normalizer
    # ------------------------------------------------------------------

    def _build_normalizer(self, node: PipelineNode, t: TransformationDef) -> None:
        g = self.graph
        s = self.script
        upstream = g.primary_upstream(node.instance_name)
        in_df = self._node_output.get(upstream, "df_UNKNOWN") if upstream else "df_UNKNOWN"
        out_df = g.df_var(node.instance_name)
        self._node_output[node.instance_name] = out_df

        s.section(f"NORMALIZER: {node.instance_name}")
        s.todo(
            f"NORMALIZER requires manual translation. "
            "Use F.explode() for array columns or F.stack() for pivoted columns. "
            "Review the source column structure before implementing."
        )
        s.emit(f"# Example: if normalizing repeated column groups (COL_1, COL_2, COL_3):")
        s.emit(f"# {out_df} = {in_df}.select(")
        s.emit(f'#     F.col("key_column"),')
        s.emit(f'#     F.explode(F.array(F.col("COL_1"), F.col("COL_2"), F.col("COL_3"))).alias("value")')
        s.emit(f"# )")
        s.emit(f"{out_df} = {in_df}  # TODO: implement NORMALIZER logic")

    # ------------------------------------------------------------------
    # Target
    # ------------------------------------------------------------------

    def _build_target(self, node: PipelineNode) -> None:
        g = self.graph
        s = self.script
        upstream = g.primary_upstream(node.instance_name)
        in_df = self._node_output.get(upstream, "df_UNKNOWN") if upstream else "df_UNKNOWN"

        tgt_def = self.folder.targets.get(node.transformation_name)
        db_type = tgt_def.db_type if tgt_def else "Unknown"
        db_name = tgt_def.db_name if tgt_def else ""
        owner = (tgt_def.owner + ".") if (tgt_def and tgt_def.owner) else ""
        tgt_name = node.transformation_name

        # Select only the columns that the mapping writes to this target
        out_fields = g.output_fields(upstream) if upstream else []

        s.section(f"TARGET: {tgt_name}  ({db_type} / {db_name})")
        s.emit(f"logger.info('Writing target: {tgt_name}')")

        if out_fields:
            col_list = ", ".join(f'F.col("{c}")' for c in out_fields)
            s.emit(f"df_output_{_safe_var(tgt_name)} = {in_df}.select({col_list})")
            write_df = f"df_output_{_safe_var(tgt_name)}"
        else:
            write_df = in_df

        if _is_lakehouse(db_type):
            self._build_lakehouse_target(node, tgt_def, write_df, db_type)
        else:
            self._build_jdbc_target(node, tgt_def, tgt_name, owner, write_df, db_type)

    def _build_jdbc_target(
        self, node: PipelineNode, tgt_def: Optional[TargetDef],
        tgt_name: str, owner: str, write_df: str, db_type: str,
    ) -> None:
        s = self.script
        conn_arg = _arg_name(f"CONN_TGT_{tgt_name}")
        s.add_arg(conn_arg)
        conn_type = _glue_conn_type(db_type)
        table_ref = f"{owner}{tgt_name}"

        s.emit(f"glueContext.write_dynamic_frame.from_options(")
        s.emit(f"    frame=DynamicFrame.fromDF({write_df}, glueContext, '{_safe_var(tgt_name)}'),")
        s.emit(f'    connection_type="{conn_type}",')
        s.emit(f"    connection_options={{")
        s.emit(f'        "useConnectionProperties": "true",')
        s.emit(f'        "dbtable": "{table_ref}",')
        s.emit(f'        "connectionName": args["{conn_arg}"],')
        s.emit(f"    }},")
        s.emit(f")")

    def _build_lakehouse_target(
        self, node: PipelineNode, tgt_def: Optional[TargetDef],
        write_df: str, db_type: str,
    ) -> None:
        s = self.script
        s.add_arg("S3_OUTPUT_PATH")
        db_type_lower = db_type.lower()

        if "delta" in db_type_lower:
            s.emit(f"# Writing to Delta Lake")
            s.emit(f"({write_df}.write")
            s.emit(f'    .format("delta")')
            s.emit(f'    .mode("overwrite")   # TODO: change to "append" or "merge" as needed')
            s.emit(f'    .save(args["S3_OUTPUT_PATH"]))')
        else:
            fmt = "parquet"
            if "orc" in db_type_lower:
                fmt = "orc"
            s.emit(f"# Writing to S3 as {fmt.upper()}")
            s.emit(f"({write_df}.write")
            s.emit(f'    .format("{fmt}")')
            s.emit(f'    .mode("overwrite")')
            s.emit(f'    .option("compression", "snappy")')
            s.emit(f'    .save(args["S3_OUTPUT_PATH"]))')

    # ------------------------------------------------------------------
    # Dispatch
    # ------------------------------------------------------------------

    def _dispatch_transformation(self, node: PipelineNode, t: TransformationDef) -> None:
        dispatch = {
            TransformationType.EXPRESSION:          self._build_expression,
            TransformationType.FILTER:              self._build_filter,
            TransformationType.AGGREGATOR:          self._build_aggregator,
            TransformationType.JOINER:              self._build_joiner,
            TransformationType.LOOKUP:              self._build_lookup,
            TransformationType.ROUTER:              self._build_router,
            TransformationType.UPDATE_STRATEGY:     self._build_update_strategy,
            TransformationType.SEQUENCE_GENERATOR:  self._build_sequence_generator,
            TransformationType.SORTER:              self._build_sorter,
            TransformationType.NORMALIZER:          self._build_normalizer,
        }
        handler = dispatch.get(t.type)
        if handler:
            handler(node, t)
        else:
            g = self.graph
            upstream = g.primary_upstream(node.instance_name)
            in_df = self._node_output.get(upstream, "df_UNKNOWN") if upstream else "df_UNKNOWN"
            out_df = g.df_var(node.instance_name)
            self._node_output[node.instance_name] = out_df
            self.script.todo(
                f"Unsupported transformation type '{t.type.value}' on '{node.instance_name}' "
                "— translate manually"
            )
            self.script.emit(f"{out_df} = {in_df}  # passthrough — review above TODO")


# ---------------------------------------------------------------------------
# Public function
# ---------------------------------------------------------------------------

def build_glue_script(mapping: MappingDef, folder: FolderDef) -> Tuple[str, List[str]]:
    """
    Generate a Glue PySpark script for the given mapping.
    Returns (script_text, list_of_warnings).
    """
    builder = GlueJobCodeBuilder(mapping, folder)
    return builder.build()
