"""
Terraform HCL builder for Databricks jobs.

Generates:
  terraform/<FOLDER>/<MAPPING_NAME>.tf   — databricks_job resource
  terraform/<FOLDER>/variables.tf        — shared variable declarations (one per folder)

Design decisions:
  - One .tf file per mapping (easy PR review, easy to destroy individual jobs)
  - Shared interactive cluster for dev via existing_cluster_id variable
  - Schedule is generated as a commented-out block (placeholder)
  - Tags: ManagedBy, MigratedFrom, Folder, Environment
"""

from __future__ import annotations
import re
import textwrap
from typing import List

from pc_extractor.models import MappingDef


def _safe_var(name: str) -> str:
    return re.sub(r"[^a-z0-9_]", "_", name.lower()).strip("_")


def _tf_resource_name(mapping_name: str) -> str:
    return _safe_var(mapping_name)


def build_terraform_job(mapping: MappingDef, notebook_path: str) -> str:
    """
    Build a Terraform HCL string for a databricks_job resource.

    Args:
        mapping:        The MappingDef being generated.
        notebook_path:  Workspace path to the generated notebook.

    Returns:
        HCL string for a databricks_job resource.
    """
    resource_name = _tf_resource_name(mapping.name)
    score = mapping.complexity_score or 1
    folder = mapping.folder

    return textwrap.dedent(f"""\
        # ---------------------------------------------------------------
        # Databricks Job: {mapping.name}
        # Folder       : {folder}
        # Score        : {score}/10
        # Migrated from Informatica PowerCenter 10.5
        # ---------------------------------------------------------------

        resource "databricks_job" "{resource_name}" {{
          name = "{mapping.name}"

          existing_cluster_id = var.databricks_cluster_id

          notebook_task {{
            notebook_path = "{notebook_path}"
          }}

          # schedule {{
          #   quartz_cron_expression = "0 0 6 * * ?"
          #   timezone_id            = "UTC"
          # }}

          tags = {{
            ManagedBy   = "terraform"
            MigratedFrom = "InformaticaPowerCenter"
            Folder       = "{folder}"
            Environment  = var.environment
          }}
        }}

        output "{resource_name}_job_id" {{
          description = "Databricks job ID for {mapping.name}"
          value       = databricks_job.{resource_name}.id
        }}
    """)


def build_terraform_variables(folder_name: str) -> str:
    """
    Build a shared variables.tf for a Databricks folder.

    Args:
        folder_name: PC folder name for documentation.

    Returns:
        HCL string for variables.tf.
    """
    return textwrap.dedent(f"""\
        # ---------------------------------------------------------------
        # Shared variables for Databricks jobs in folder: {folder_name}
        # Generated by databricks-gen
        # ---------------------------------------------------------------

        variable "databricks_cluster_id" {{
          description = "Existing Databricks cluster ID used by jobs in this folder"
          type        = string
        }}

        variable "databricks_workspace_url" {{
          description = "Databricks workspace URL (e.g. https://adb-xxxx.azuredatabricks.net)"
          type        = string
        }}

        variable "environment" {{
          description = "Deployment environment"
          type        = string
          validation {{
            condition     = contains(["dev", "stage", "prod"], var.environment)
            error_message = "environment must be dev, stage, or prod"
          }}
        }}
    """)
