"""
Terraform HCL builder for Databricks jobs.

Generates:
  terraform/<FOLDER>/<MAPPING_NAME>.tf   — databricks_job resource
  terraform/<FOLDER>/variables.tf        — shared variable declarations (one per folder)

Design decisions:
  - One .tf file per mapping (easy PR review, easy to destroy individual jobs)
  - Shared interactive cluster for dev via existing_cluster_id variable
  - Schedule is generated as a commented-out block (placeholder)
  - Tags: ManagedBy, MigratedFrom, Folder, Environment
"""

from __future__ import annotations
import re
import textwrap
from typing import List

from pc_extractor.models import MappingDef


def _safe_var(name: str) -> str:
    return re.sub(r"[^a-z0-9_]", "_", name.lower()).strip("_")


def _tf_resource_name(mapping_name: str) -> str:
    return _safe_var(mapping_name)


def build_terraform_job(mapping: MappingDef, notebook_path: str) -> str:
    """
    Build a Terraform HCL string for a databricks_job resource.

    Args:
        mapping:        The MappingDef being generated.
        notebook_path:  Workspace path to the generated notebook.

    Returns:
        HCL string for a databricks_job resource.
    """
    resource_name = _tf_resource_name(mapping.name)
    score = mapping.complexity_score or 1
    folder = mapping.folder

    return textwrap.dedent(f"""\
        # ---------------------------------------------------------------
        # Databricks Job: {mapping.name}
        # Folder       : {folder}
        # Score        : {score}/10
        # Migrated from Informatica PowerCenter 10.5
        # ---------------------------------------------------------------

        resource "databricks_job" "{resource_name}" {{
          name = "{mapping.name}"

          existing_cluster_id = var.databricks_cluster_id

          notebook_task {{
            notebook_path = "{notebook_path}"
          }}

          # schedule {{
          #   quartz_cron_expression = "0 0 6 * * ?"
          #   timezone_id            = "UTC"
          # }}

          tags = {{
            ManagedBy   = "terraform"
            MigratedFrom = "InformaticaPowerCenter"
            Folder       = "{folder}"
            Environment  = var.environment
          }}
        }}

        output "{resource_name}_job_id" {{
          description = "Databricks job ID for {mapping.name}"
          value       = databricks_job.{resource_name}.id
        }}
    """)


def build_databricks_job_module() -> str:
    """Reusable Terraform module definition for a Databricks job (modules/databricks_job/main.tf)."""
    return textwrap.dedent("""\
        # ---------------------------------------------------------------
        # Reusable module: modules/databricks_job
        # Generated by pc-extractor databricks-gen --env-split
        # ---------------------------------------------------------------

        variable "job_name"        { type = string }
        variable "notebook_path"   { type = string }
        variable "cluster_id"      { type = string }
        variable "environment"     { type = string }

        resource "databricks_job" "this" {
          name                = var.job_name
          existing_cluster_id = var.cluster_id

          notebook_task {
            notebook_path = var.notebook_path
          }

          tags = {
            ManagedBy    = "terraform"
            Environment  = var.environment
            MigratedFrom = "InformaticaPowerCenter"
          }
        }

        output "job_id" {
          value = databricks_job.this.id
        }
    """)


def build_databricks_environment_main(
    folder_name: str,
    mappings: list,
    env: str,
) -> str:
    """Generate environments/<env>/main.tf calling the databricks_job module."""
    calls = []
    for name in mappings:
        safe = _safe_var(name)
        nb_path = f"/Repos/migration/{folder_name}/{name}"
        calls.append(textwrap.dedent(f"""\
            module "{safe}" {{
              source       = "../../modules/databricks_job"
              job_name     = "{name}"
              notebook_path = "{nb_path}"
              cluster_id   = var.databricks_cluster_id
              environment  = var.environment
            }}
        """))

    return textwrap.dedent(f"""\
        # ---------------------------------------------------------------
        # Environment: {env}  |  Folder: {folder_name}
        # Generated by databricks-gen --env-split
        # ---------------------------------------------------------------

        terraform {{
          required_providers {{
            databricks = {{
              source  = "databricks/databricks"
              version = "~> 1.0"
            }}
          }}
        }}

        provider "databricks" {{
          host = var.databricks_workspace_url
        }}

    """) + "\n".join(calls)


def build_databricks_environment_variables() -> str:
    return textwrap.dedent("""\
        variable "environment"               { type = string }
        variable "databricks_cluster_id"     { type = string }
        variable "databricks_workspace_url"  { type = string }
    """)


def build_databricks_environment_tfvars(env: str, workspace_url: str = "", cluster_id: str = "") -> str:
    return textwrap.dedent(f"""\
        environment                = "{env}"
        databricks_workspace_url   = "{workspace_url or 'https://adb-XXXX.azuredatabricks.net'}"
        databricks_cluster_id      = "{cluster_id or 'CLUSTER_ID'}"  # TODO: set per environment
    """)


def build_databricks_backend_tf(
    env: str,
    s3_bucket: str = "",
    dynamodb_table: str = "",
    aws_region: str = "us-east-1",
    folder_name: str = "",
) -> str:
    bucket = s3_bucket or "terraform-state-bucket"
    table  = dynamodb_table or "terraform-state-lock"
    key    = f"databricks/{folder_name}/{env}/terraform.tfstate" if folder_name else f"databricks/{env}/terraform.tfstate"
    return textwrap.dedent(f"""\
        terraform {{
          backend "s3" {{
            bucket         = "{bucket}"
            key            = "{key}"
            region         = "{aws_region}"
            encrypt        = true
            dynamodb_table = "{table}"
          }}
        }}
    """)


def build_terraform_variables(folder_name: str) -> str:
    """
    Build a shared variables.tf for a Databricks folder.

    Args:
        folder_name: PC folder name for documentation.

    Returns:
        HCL string for variables.tf.
    """
    return textwrap.dedent(f"""\
        # ---------------------------------------------------------------
        # Shared variables for Databricks jobs in folder: {folder_name}
        # Generated by databricks-gen
        # ---------------------------------------------------------------

        variable "databricks_cluster_id" {{
          description = "Existing Databricks cluster ID used by jobs in this folder"
          type        = string
        }}

        variable "databricks_workspace_url" {{
          description = "Databricks workspace URL (e.g. https://adb-xxxx.azuredatabricks.net)"
          type        = string
        }}

        variable "environment" {{
          description = "Deployment environment"
          type        = string
          validation {{
            condition     = contains(["dev", "stage", "prod"], var.environment)
            error_message = "environment must be dev, stage, or prod"
          }}
        }}
    """)
